---
- hosts: all
  gather_facts: false
  become: true
  remote_user: ec2-user
  become_user: root
  tasks:
  - name: Copy file from src to dest
    synchronize:
      src: /var/jenkins_home/workspace/VeoliaWatersFrontend/frontend/build/
      dest: /var/www/html/